//go:build go1.22

// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for WorkoutStatus.
const (
	ABANDONED WorkoutStatus = "ABANDONED"
	COMPLETED WorkoutStatus = "COMPLETED"
	PENDING   WorkoutStatus = "PENDING"
)

// PromptRequest defines model for PromptRequest.
type PromptRequest struct {
	Prompt string `json:"prompt"`
}

// Workout defines model for Workout.
type Workout struct {
	// Content Structured workout plan (implementation-specific)
	Content   *map[string]interface{} `json:"content,omitempty"`
	CreatedAt time.Time               `json:"created_at"`
	Id        string                  `json:"id"`

	// Prompt Original generation prompt
	Prompt    *string       `json:"prompt,omitempty"`
	Status    WorkoutStatus `json:"status"`
	UpdatedAt *time.Time    `json:"updated_at,omitempty"`
}

// WorkoutStatus defines model for Workout.Status.
type WorkoutStatus string

// WorkoutList defines model for WorkoutList.
type WorkoutList struct {
	Items  []Workout `json:"items"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
	Total  *int      `json:"total,omitempty"`
}

// GetV1WorkoutsParams defines parameters for GetV1Workouts.
type GetV1WorkoutsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostV1WorkoutsJSONRequestBody defines body for PostV1Workouts for application/json ContentType.
type PostV1WorkoutsJSONRequestBody = PromptRequest

// PostV1WorkoutsCurrentAdjustJSONRequestBody defines body for PostV1WorkoutsCurrentAdjust for application/json ContentType.
type PostV1WorkoutsCurrentAdjustJSONRequestBody = PromptRequest

// PostV1WorkoutsCurrentCompleteJSONRequestBody defines body for PostV1WorkoutsCurrentComplete for application/json ContentType.
type PostV1WorkoutsCurrentCompleteJSONRequestBody = PromptRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1Workouts request
	GetV1Workouts(ctx context.Context, params *GetV1WorkoutsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1WorkoutsWithBody request with any body
	PostV1WorkoutsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1Workouts(ctx context.Context, body PostV1WorkoutsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV1WorkoutsCurrent request
	DeleteV1WorkoutsCurrent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1WorkoutsCurrent request
	GetV1WorkoutsCurrent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1WorkoutsCurrentAdjustWithBody request with any body
	PostV1WorkoutsCurrentAdjustWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1WorkoutsCurrentAdjust(ctx context.Context, body PostV1WorkoutsCurrentAdjustJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1WorkoutsCurrentCompleteWithBody request with any body
	PostV1WorkoutsCurrentCompleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1WorkoutsCurrentComplete(ctx context.Context, body PostV1WorkoutsCurrentCompleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1WorkoutsId request
	GetV1WorkoutsId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1Workouts(ctx context.Context, params *GetV1WorkoutsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1WorkoutsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1WorkoutsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1WorkoutsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Workouts(ctx context.Context, body PostV1WorkoutsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1WorkoutsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV1WorkoutsCurrent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV1WorkoutsCurrentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1WorkoutsCurrent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1WorkoutsCurrentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1WorkoutsCurrentAdjustWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1WorkoutsCurrentAdjustRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1WorkoutsCurrentAdjust(ctx context.Context, body PostV1WorkoutsCurrentAdjustJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1WorkoutsCurrentAdjustRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1WorkoutsCurrentCompleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1WorkoutsCurrentCompleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1WorkoutsCurrentComplete(ctx context.Context, body PostV1WorkoutsCurrentCompleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1WorkoutsCurrentCompleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1WorkoutsId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1WorkoutsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1WorkoutsRequest generates requests for GetV1Workouts
func NewGetV1WorkoutsRequest(server string, params *GetV1WorkoutsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1WorkoutsRequest calls the generic PostV1Workouts builder with application/json body
func NewPostV1WorkoutsRequest(server string, body PostV1WorkoutsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1WorkoutsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1WorkoutsRequestWithBody generates requests for PostV1Workouts with any type of body
func NewPostV1WorkoutsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteV1WorkoutsCurrentRequest generates requests for DeleteV1WorkoutsCurrent
func NewDeleteV1WorkoutsCurrentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts/current")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1WorkoutsCurrentRequest generates requests for GetV1WorkoutsCurrent
func NewGetV1WorkoutsCurrentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts/current")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1WorkoutsCurrentAdjustRequest calls the generic PostV1WorkoutsCurrentAdjust builder with application/json body
func NewPostV1WorkoutsCurrentAdjustRequest(server string, body PostV1WorkoutsCurrentAdjustJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1WorkoutsCurrentAdjustRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1WorkoutsCurrentAdjustRequestWithBody generates requests for PostV1WorkoutsCurrentAdjust with any type of body
func NewPostV1WorkoutsCurrentAdjustRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts/current/adjust")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostV1WorkoutsCurrentCompleteRequest calls the generic PostV1WorkoutsCurrentComplete builder with application/json body
func NewPostV1WorkoutsCurrentCompleteRequest(server string, body PostV1WorkoutsCurrentCompleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1WorkoutsCurrentCompleteRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1WorkoutsCurrentCompleteRequestWithBody generates requests for PostV1WorkoutsCurrentComplete with any type of body
func NewPostV1WorkoutsCurrentCompleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts/current/complete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetV1WorkoutsIdRequest generates requests for GetV1WorkoutsId
func NewGetV1WorkoutsIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workouts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1WorkoutsWithResponse request
	GetV1WorkoutsWithResponse(ctx context.Context, params *GetV1WorkoutsParams, reqEditors ...RequestEditorFn) (*GetV1WorkoutsResponse, error)

	// PostV1WorkoutsWithBodyWithResponse request with any body
	PostV1WorkoutsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1WorkoutsResponse, error)

	PostV1WorkoutsWithResponse(ctx context.Context, body PostV1WorkoutsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1WorkoutsResponse, error)

	// DeleteV1WorkoutsCurrentWithResponse request
	DeleteV1WorkoutsCurrentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteV1WorkoutsCurrentResponse, error)

	// GetV1WorkoutsCurrentWithResponse request
	GetV1WorkoutsCurrentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WorkoutsCurrentResponse, error)

	// PostV1WorkoutsCurrentAdjustWithBodyWithResponse request with any body
	PostV1WorkoutsCurrentAdjustWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentAdjustResponse, error)

	PostV1WorkoutsCurrentAdjustWithResponse(ctx context.Context, body PostV1WorkoutsCurrentAdjustJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentAdjustResponse, error)

	// PostV1WorkoutsCurrentCompleteWithBodyWithResponse request with any body
	PostV1WorkoutsCurrentCompleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentCompleteResponse, error)

	PostV1WorkoutsCurrentCompleteWithResponse(ctx context.Context, body PostV1WorkoutsCurrentCompleteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentCompleteResponse, error)

	// GetV1WorkoutsIdWithResponse request
	GetV1WorkoutsIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1WorkoutsIdResponse, error)
}

type GetV1WorkoutsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WorkoutList
}

// Status returns HTTPResponse.Status
func (r GetV1WorkoutsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1WorkoutsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1WorkoutsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Workout
}

// Status returns HTTPResponse.Status
func (r PostV1WorkoutsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1WorkoutsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteV1WorkoutsCurrentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteV1WorkoutsCurrentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteV1WorkoutsCurrentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1WorkoutsCurrentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Workout
}

// Status returns HTTPResponse.Status
func (r GetV1WorkoutsCurrentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1WorkoutsCurrentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1WorkoutsCurrentAdjustResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Workout
}

// Status returns HTTPResponse.Status
func (r PostV1WorkoutsCurrentAdjustResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1WorkoutsCurrentAdjustResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1WorkoutsCurrentCompleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Workout
}

// Status returns HTTPResponse.Status
func (r PostV1WorkoutsCurrentCompleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1WorkoutsCurrentCompleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1WorkoutsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Workout
}

// Status returns HTTPResponse.Status
func (r GetV1WorkoutsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1WorkoutsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1WorkoutsWithResponse request returning *GetV1WorkoutsResponse
func (c *ClientWithResponses) GetV1WorkoutsWithResponse(ctx context.Context, params *GetV1WorkoutsParams, reqEditors ...RequestEditorFn) (*GetV1WorkoutsResponse, error) {
	rsp, err := c.GetV1Workouts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1WorkoutsResponse(rsp)
}

// PostV1WorkoutsWithBodyWithResponse request with arbitrary body returning *PostV1WorkoutsResponse
func (c *ClientWithResponses) PostV1WorkoutsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1WorkoutsResponse, error) {
	rsp, err := c.PostV1WorkoutsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1WorkoutsResponse(rsp)
}

func (c *ClientWithResponses) PostV1WorkoutsWithResponse(ctx context.Context, body PostV1WorkoutsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1WorkoutsResponse, error) {
	rsp, err := c.PostV1Workouts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1WorkoutsResponse(rsp)
}

// DeleteV1WorkoutsCurrentWithResponse request returning *DeleteV1WorkoutsCurrentResponse
func (c *ClientWithResponses) DeleteV1WorkoutsCurrentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteV1WorkoutsCurrentResponse, error) {
	rsp, err := c.DeleteV1WorkoutsCurrent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV1WorkoutsCurrentResponse(rsp)
}

// GetV1WorkoutsCurrentWithResponse request returning *GetV1WorkoutsCurrentResponse
func (c *ClientWithResponses) GetV1WorkoutsCurrentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WorkoutsCurrentResponse, error) {
	rsp, err := c.GetV1WorkoutsCurrent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1WorkoutsCurrentResponse(rsp)
}

// PostV1WorkoutsCurrentAdjustWithBodyWithResponse request with arbitrary body returning *PostV1WorkoutsCurrentAdjustResponse
func (c *ClientWithResponses) PostV1WorkoutsCurrentAdjustWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentAdjustResponse, error) {
	rsp, err := c.PostV1WorkoutsCurrentAdjustWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1WorkoutsCurrentAdjustResponse(rsp)
}

func (c *ClientWithResponses) PostV1WorkoutsCurrentAdjustWithResponse(ctx context.Context, body PostV1WorkoutsCurrentAdjustJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentAdjustResponse, error) {
	rsp, err := c.PostV1WorkoutsCurrentAdjust(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1WorkoutsCurrentAdjustResponse(rsp)
}

// PostV1WorkoutsCurrentCompleteWithBodyWithResponse request with arbitrary body returning *PostV1WorkoutsCurrentCompleteResponse
func (c *ClientWithResponses) PostV1WorkoutsCurrentCompleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentCompleteResponse, error) {
	rsp, err := c.PostV1WorkoutsCurrentCompleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1WorkoutsCurrentCompleteResponse(rsp)
}

func (c *ClientWithResponses) PostV1WorkoutsCurrentCompleteWithResponse(ctx context.Context, body PostV1WorkoutsCurrentCompleteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1WorkoutsCurrentCompleteResponse, error) {
	rsp, err := c.PostV1WorkoutsCurrentComplete(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1WorkoutsCurrentCompleteResponse(rsp)
}

// GetV1WorkoutsIdWithResponse request returning *GetV1WorkoutsIdResponse
func (c *ClientWithResponses) GetV1WorkoutsIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1WorkoutsIdResponse, error) {
	rsp, err := c.GetV1WorkoutsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1WorkoutsIdResponse(rsp)
}

// ParseGetV1WorkoutsResponse parses an HTTP response from a GetV1WorkoutsWithResponse call
func ParseGetV1WorkoutsResponse(rsp *http.Response) (*GetV1WorkoutsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1WorkoutsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WorkoutList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1WorkoutsResponse parses an HTTP response from a PostV1WorkoutsWithResponse call
func ParsePostV1WorkoutsResponse(rsp *http.Response) (*PostV1WorkoutsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1WorkoutsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Workout
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteV1WorkoutsCurrentResponse parses an HTTP response from a DeleteV1WorkoutsCurrentWithResponse call
func ParseDeleteV1WorkoutsCurrentResponse(rsp *http.Response) (*DeleteV1WorkoutsCurrentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteV1WorkoutsCurrentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV1WorkoutsCurrentResponse parses an HTTP response from a GetV1WorkoutsCurrentWithResponse call
func ParseGetV1WorkoutsCurrentResponse(rsp *http.Response) (*GetV1WorkoutsCurrentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1WorkoutsCurrentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Workout
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1WorkoutsCurrentAdjustResponse parses an HTTP response from a PostV1WorkoutsCurrentAdjustWithResponse call
func ParsePostV1WorkoutsCurrentAdjustResponse(rsp *http.Response) (*PostV1WorkoutsCurrentAdjustResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1WorkoutsCurrentAdjustResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Workout
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostV1WorkoutsCurrentCompleteResponse parses an HTTP response from a PostV1WorkoutsCurrentCompleteWithResponse call
func ParsePostV1WorkoutsCurrentCompleteResponse(rsp *http.Response) (*PostV1WorkoutsCurrentCompleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1WorkoutsCurrentCompleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Workout
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetV1WorkoutsIdResponse parses an HTTP response from a GetV1WorkoutsIdWithResponse call
func ParseGetV1WorkoutsIdResponse(rsp *http.Response) (*GetV1WorkoutsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1WorkoutsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Workout
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List workouts
	// (GET /v1/workouts)
	GetV1Workouts(w http.ResponseWriter, r *http.Request, params GetV1WorkoutsParams)
	// Generate a new workout
	// (POST /v1/workouts)
	PostV1Workouts(w http.ResponseWriter, r *http.Request)
	// Abandon current workout
	// (DELETE /v1/workouts/current)
	DeleteV1WorkoutsCurrent(w http.ResponseWriter, r *http.Request)
	// Get current pending workout
	// (GET /v1/workouts/current)
	GetV1WorkoutsCurrent(w http.ResponseWriter, r *http.Request)
	// Adjust current workout
	// (POST /v1/workouts/current/adjust)
	PostV1WorkoutsCurrentAdjust(w http.ResponseWriter, r *http.Request)
	// Complete current workout
	// (POST /v1/workouts/current/complete)
	PostV1WorkoutsCurrentComplete(w http.ResponseWriter, r *http.Request)
	// Get workout by ID
	// (GET /v1/workouts/{id})
	GetV1WorkoutsId(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetV1Workouts operation middleware
func (siw *ServerInterfaceWrapper) GetV1Workouts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1WorkoutsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Workouts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1Workouts operation middleware
func (siw *ServerInterfaceWrapper) PostV1Workouts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Workouts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1WorkoutsCurrent operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1WorkoutsCurrent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1WorkoutsCurrent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1WorkoutsCurrent operation middleware
func (siw *ServerInterfaceWrapper) GetV1WorkoutsCurrent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1WorkoutsCurrent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1WorkoutsCurrentAdjust operation middleware
func (siw *ServerInterfaceWrapper) PostV1WorkoutsCurrentAdjust(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1WorkoutsCurrentAdjust(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1WorkoutsCurrentComplete operation middleware
func (siw *ServerInterfaceWrapper) PostV1WorkoutsCurrentComplete(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1WorkoutsCurrentComplete(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1WorkoutsId operation middleware
func (siw *ServerInterfaceWrapper) GetV1WorkoutsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1WorkoutsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/v1/workouts", wrapper.GetV1Workouts)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workouts", wrapper.PostV1Workouts)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/workouts/current", wrapper.DeleteV1WorkoutsCurrent)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workouts/current", wrapper.GetV1WorkoutsCurrent)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workouts/current/adjust", wrapper.PostV1WorkoutsCurrentAdjust)
	m.HandleFunc("POST "+options.BaseURL+"/v1/workouts/current/complete", wrapper.PostV1WorkoutsCurrentComplete)
	m.HandleFunc("GET "+options.BaseURL+"/v1/workouts/{id}", wrapper.GetV1WorkoutsId)

	return m
}

type GetV1WorkoutsRequestObject struct {
	Params GetV1WorkoutsParams
}

type GetV1WorkoutsResponseObject interface {
	VisitGetV1WorkoutsResponse(w http.ResponseWriter) error
}

type GetV1Workouts200JSONResponse WorkoutList

func (response GetV1Workouts200JSONResponse) VisitGetV1WorkoutsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostV1WorkoutsRequestObject struct {
	Body *PostV1WorkoutsJSONRequestBody
}

type PostV1WorkoutsResponseObject interface {
	VisitPostV1WorkoutsResponse(w http.ResponseWriter) error
}

type PostV1Workouts201JSONResponse Workout

func (response PostV1Workouts201JSONResponse) VisitPostV1WorkoutsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostV1Workouts409Response struct {
}

func (response PostV1Workouts409Response) VisitPostV1WorkoutsResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type DeleteV1WorkoutsCurrentRequestObject struct {
}

type DeleteV1WorkoutsCurrentResponseObject interface {
	VisitDeleteV1WorkoutsCurrentResponse(w http.ResponseWriter) error
}

type DeleteV1WorkoutsCurrent204Response struct {
}

func (response DeleteV1WorkoutsCurrent204Response) VisitDeleteV1WorkoutsCurrentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteV1WorkoutsCurrent404Response struct {
}

func (response DeleteV1WorkoutsCurrent404Response) VisitDeleteV1WorkoutsCurrentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetV1WorkoutsCurrentRequestObject struct {
}

type GetV1WorkoutsCurrentResponseObject interface {
	VisitGetV1WorkoutsCurrentResponse(w http.ResponseWriter) error
}

type GetV1WorkoutsCurrent200JSONResponse Workout

func (response GetV1WorkoutsCurrent200JSONResponse) VisitGetV1WorkoutsCurrentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetV1WorkoutsCurrent404Response struct {
}

func (response GetV1WorkoutsCurrent404Response) VisitGetV1WorkoutsCurrentResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostV1WorkoutsCurrentAdjustRequestObject struct {
	Body *PostV1WorkoutsCurrentAdjustJSONRequestBody
}

type PostV1WorkoutsCurrentAdjustResponseObject interface {
	VisitPostV1WorkoutsCurrentAdjustResponse(w http.ResponseWriter) error
}

type PostV1WorkoutsCurrentAdjust200JSONResponse Workout

func (response PostV1WorkoutsCurrentAdjust200JSONResponse) VisitPostV1WorkoutsCurrentAdjustResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostV1WorkoutsCurrentAdjust404Response struct {
}

func (response PostV1WorkoutsCurrentAdjust404Response) VisitPostV1WorkoutsCurrentAdjustResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostV1WorkoutsCurrentCompleteRequestObject struct {
	Body *PostV1WorkoutsCurrentCompleteJSONRequestBody
}

type PostV1WorkoutsCurrentCompleteResponseObject interface {
	VisitPostV1WorkoutsCurrentCompleteResponse(w http.ResponseWriter) error
}

type PostV1WorkoutsCurrentComplete200JSONResponse Workout

func (response PostV1WorkoutsCurrentComplete200JSONResponse) VisitPostV1WorkoutsCurrentCompleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostV1WorkoutsCurrentComplete404Response struct {
}

func (response PostV1WorkoutsCurrentComplete404Response) VisitPostV1WorkoutsCurrentCompleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetV1WorkoutsIdRequestObject struct {
	Id string `json:"id"`
}

type GetV1WorkoutsIdResponseObject interface {
	VisitGetV1WorkoutsIdResponse(w http.ResponseWriter) error
}

type GetV1WorkoutsId200JSONResponse Workout

func (response GetV1WorkoutsId200JSONResponse) VisitGetV1WorkoutsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetV1WorkoutsId404Response struct {
}

func (response GetV1WorkoutsId404Response) VisitGetV1WorkoutsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List workouts
	// (GET /v1/workouts)
	GetV1Workouts(ctx context.Context, request GetV1WorkoutsRequestObject) (GetV1WorkoutsResponseObject, error)
	// Generate a new workout
	// (POST /v1/workouts)
	PostV1Workouts(ctx context.Context, request PostV1WorkoutsRequestObject) (PostV1WorkoutsResponseObject, error)
	// Abandon current workout
	// (DELETE /v1/workouts/current)
	DeleteV1WorkoutsCurrent(ctx context.Context, request DeleteV1WorkoutsCurrentRequestObject) (DeleteV1WorkoutsCurrentResponseObject, error)
	// Get current pending workout
	// (GET /v1/workouts/current)
	GetV1WorkoutsCurrent(ctx context.Context, request GetV1WorkoutsCurrentRequestObject) (GetV1WorkoutsCurrentResponseObject, error)
	// Adjust current workout
	// (POST /v1/workouts/current/adjust)
	PostV1WorkoutsCurrentAdjust(ctx context.Context, request PostV1WorkoutsCurrentAdjustRequestObject) (PostV1WorkoutsCurrentAdjustResponseObject, error)
	// Complete current workout
	// (POST /v1/workouts/current/complete)
	PostV1WorkoutsCurrentComplete(ctx context.Context, request PostV1WorkoutsCurrentCompleteRequestObject) (PostV1WorkoutsCurrentCompleteResponseObject, error)
	// Get workout by ID
	// (GET /v1/workouts/{id})
	GetV1WorkoutsId(ctx context.Context, request GetV1WorkoutsIdRequestObject) (GetV1WorkoutsIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetV1Workouts operation middleware
func (sh *strictHandler) GetV1Workouts(w http.ResponseWriter, r *http.Request, params GetV1WorkoutsParams) {
	var request GetV1WorkoutsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1Workouts(ctx, request.(GetV1WorkoutsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1Workouts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1WorkoutsResponseObject); ok {
		if err := validResponse.VisitGetV1WorkoutsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostV1Workouts operation middleware
func (sh *strictHandler) PostV1Workouts(w http.ResponseWriter, r *http.Request) {
	var request PostV1WorkoutsRequestObject

	var body PostV1WorkoutsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostV1Workouts(ctx, request.(PostV1WorkoutsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostV1Workouts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostV1WorkoutsResponseObject); ok {
		if err := validResponse.VisitPostV1WorkoutsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteV1WorkoutsCurrent operation middleware
func (sh *strictHandler) DeleteV1WorkoutsCurrent(w http.ResponseWriter, r *http.Request) {
	var request DeleteV1WorkoutsCurrentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteV1WorkoutsCurrent(ctx, request.(DeleteV1WorkoutsCurrentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteV1WorkoutsCurrent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteV1WorkoutsCurrentResponseObject); ok {
		if err := validResponse.VisitDeleteV1WorkoutsCurrentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetV1WorkoutsCurrent operation middleware
func (sh *strictHandler) GetV1WorkoutsCurrent(w http.ResponseWriter, r *http.Request) {
	var request GetV1WorkoutsCurrentRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1WorkoutsCurrent(ctx, request.(GetV1WorkoutsCurrentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1WorkoutsCurrent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1WorkoutsCurrentResponseObject); ok {
		if err := validResponse.VisitGetV1WorkoutsCurrentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostV1WorkoutsCurrentAdjust operation middleware
func (sh *strictHandler) PostV1WorkoutsCurrentAdjust(w http.ResponseWriter, r *http.Request) {
	var request PostV1WorkoutsCurrentAdjustRequestObject

	var body PostV1WorkoutsCurrentAdjustJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostV1WorkoutsCurrentAdjust(ctx, request.(PostV1WorkoutsCurrentAdjustRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostV1WorkoutsCurrentAdjust")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostV1WorkoutsCurrentAdjustResponseObject); ok {
		if err := validResponse.VisitPostV1WorkoutsCurrentAdjustResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostV1WorkoutsCurrentComplete operation middleware
func (sh *strictHandler) PostV1WorkoutsCurrentComplete(w http.ResponseWriter, r *http.Request) {
	var request PostV1WorkoutsCurrentCompleteRequestObject

	var body PostV1WorkoutsCurrentCompleteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostV1WorkoutsCurrentComplete(ctx, request.(PostV1WorkoutsCurrentCompleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostV1WorkoutsCurrentComplete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostV1WorkoutsCurrentCompleteResponseObject); ok {
		if err := validResponse.VisitPostV1WorkoutsCurrentCompleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetV1WorkoutsId operation middleware
func (sh *strictHandler) GetV1WorkoutsId(w http.ResponseWriter, r *http.Request, id string) {
	var request GetV1WorkoutsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetV1WorkoutsId(ctx, request.(GetV1WorkoutsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetV1WorkoutsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetV1WorkoutsIdResponseObject); ok {
		if err := validResponse.VisitGetV1WorkoutsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXT2/buBP9KgR/v8PuQpGVJpfq5sZBYKBNjLa7OTTBghFHNlOJZMhhEiPwd1+Q+mtL",
	"Tna3Qbo+ieKIM/Pem+H4iWaq1EqCREvTJ2qzFZQsPC6MKjV+hjsHFv0LbZQGgwJsvSp1eI9rDTSlFo2Q",
	"S7rZRNTAnRMGOE2/NXbXUWOnbm4hQ7qJ6KUy35UbOTtTEkGGDca5QKEkKxY9EzQOIsrBZkZov01T+gWN",
	"y9AZ4OShOpjogknyiyh1ASVIZN7ywGrIRC6yX+lISJkBhsD/ZMF5rkzpnyhnCAcoSui+adKNqOAjKEQ9",
	"gLbjvDBiKSQryBIkmBATqW1HDrfI0AVQQLrSA7o4PZ/Nz89oRE8uPi0+nn49ndGITj9Mz2cX56ezHtLd",
	"KU7zf5jWDouC0zaWLZSe4fWjGNONQCi3H/5vIKcp/d+kk+Kk1uGkkcimdcOMYWu/LkQp+voTEmEJxm+p",
	"PLewZw8VsmJsazfjEF7jpj1zmK//UMhcDZmeLuYkV6YlWi4jwvits/Wj5MSnXIBfN6K18ZW8knXexEMO",
	"pGTZSkhIryQhB+SLf2dTUgshIq0OItLKoDKdIimVRaIkNOZdcYAhzoKpLL8aJm2oNBvc+N9v7TcHVy5J",
	"jqDztN+kF4FXlcDCg9XkM13MaUTvwdgKosM4iZNAmQbJtKApPYqT+IhGVDNcBX1M7g8nDTh+vYSRqvJi",
	"s4QVRYtjgB5XQJjDFUgUmddsSJk8CFwRzXwd+u9jGgKoinHOaUrPAP84vGyc+mAMKwHBWJp+e6LCu7xz",
	"YNY0opKVPsVGKJV0qwhz5gqk6bskoiV7FKWv4MPEr4SsV9GIEMcd1Aoc9dA/Mhk58tqL22olbVWF75Jk",
	"t9FqXXiIhJKTW+sxfeo5+hs1Gso9VMM2M4sKZuCkEF6KectQqDnrypKZdU1hby+iWtkRps+qagJLGJHw",
	"0OpZyFaLoWriK/kZ0BlpyXHynpwomRciQyJywgbFwAoDjK8JPHodxUG724pYKLstCVPdjB8UX78alNt3",
	"7ma7J/lLbzPg8fC1eRzjsCnfuvF7co6T9yMdj2iQvNfNdoDdYbyhcpvJYNQv+knmjKnT41AAwtDzJ2a+",
	"21DutfGQYtv1pmHBz8K5HcEntcsB3sdD3w067IZJrmSDz4jludoFaAeRaXVEm8RDd/+Ntr1G4T7x3YSV",
	"IcfJsde79P2/lvbzrW5v2slbyKz2PsTo38J5BthCOWY5prJJdUWHyWW0Af0ehqlxzG+YBU6U9Ipm6Awr",
	"SMHk0rEl1ENe/EJnqTGYVkH8Z9rMm/BfIct/nPcKvWEV7aO8HsPgh0mvOA6jHXYTFRFIUHXT08v3S62C",
	"kyauN9LBT+K9SfMVmG+Oepn7J8E3vXHymaY453smQD+idvNZ+I+0XUf9WW33D9b1z8H68gWEm8tMKiS5",
	"cpKPtNRW+Gsyn1VOLJj7BhtnCprSFaK26WTCtIjhkXla4kyVdHO9+SsAAP//ujGC43YQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
